# JBrowse

# much of this could be moved to a new base image (ie,
# build jbrowse in the base container then in this
# container just bring in the gen names script and execute
#
# Usage:
#  docker build -f Dockerfile.genNames -t sgd_gennames --no-cache .  
#      #note that the no-cache will probably be needed since changes will probably
#      #happen in the gen-names.sh script
#  docker run -e "AWS_ACCESS_KEY=<access>" -e "AWS_SECRET_KEY=<secret>" --rm sgd_gennames

FROM gmod/jbrowse-buildenv:latest as build
LABEL maintainer="scott@scottcain.net"

# Actual JBrowse code; can bump the release tag and rebuild to get new versions
RUN git clone --single-branch --branch support_old_sgd https://github.com/GMOD/jbrowse.git

#agr_jbrowse_config contains the configuration files for the various species; they are
#moved into the right place in the long RUN command below
#RUN git clone --single-branch --branch release-3.1.1 https://github.com/alliance-genome/agr_jbrowse_config.git
RUN git clone --single-branch --branch generate_names_docker https://github.com/alliance-genome/agr_jbrowse_sgd.git

RUN mkdir /usr/share/nginx/html/jbrowse

RUN rm /usr/share/nginx/html/index.html && rm /usr/share/nginx/html/50x.html && cp -r /jbrowse/* /usr/share/nginx/html/jbrowse && \
    cp /jbrowse/.htaccess /usr/share/nginx/html/jbrowse/.htaccess && \
    cp -r /agr_jbrowse_sgd/jbrowse/data /usr/share/nginx/html/jbrowse && \
    cp /agr_jbrowse_sgd/jbrowse/jbrowse.conf /usr/share/nginx/html/jbrowse && \
    cp /agr_jbrowse_sgd/gen_names.sh / && \
    cp /agr_jbrowse_sgd/jbrowse/jbrowse_conf.json /usr/share/nginx/html/jbrowse

WORKDIR  /usr/share/nginx/html/jbrowse
RUN ./setup.sh

#All of this was moved to the CMD script
#WORKDIR /usr/share/nginx/html/jbrowse/data

#RUN aws s3 cp --recursive s3://agrjbrowse/MOD-jbrowses/SGD/jbrowse/data/seq seq/ 
#RUN curl -O https://stage.dh18454tea1gu.amplifyapp.com/data/trackList.json
#RUN curl -O https://stage.dh18454tea1gu.amplifyapp.com/data/tracks.conf
#RUN aws s3 cp --recursive s3://agrjbrowse/MOD-jbrowses/SGD/jbrowse/data/tracks tracks/

# convert absolut templateUrls to relataive
#RUN sed -i 's/https:.*SGD\/jbrowse\///g' trackList.json
#RUN sed -i 's/https:.*SGD\/jbrowse\/data\///g' tracks.conf

#WORKDIR /usr/share/nginx/html/jbrowse

CMD ["/bin/bash", "/gen_names.sh"]
